services:
  call_login.entrypoint:
    class: vBridgeCloud\CallLoginBundle\Auth\AuthEntryPoint
    arguments:
      [ '@?', '@?', '@?', '@router.default' ]
  call_login.authenticator:
    class: vBridgeCloud\CallLoginBundle\Auth\JwtAuthenticator
    arguments:
      [ '@?', '@?', '@?', '@?', '@?', '@?', '@router.default' ]
  call_login.user_provider:
    class: vBridgeCloud\CallLoginBundle\Auth\UserProvider
    arguments:
      [ '@request_stack', '@request_stack' ]
